# Customer Support Agent Configuration
# Main configuration file for the Customer Support Agent

agent:
  name: "Customer Support Agent"
  version: "1.0.0"
  description: "Intelligent customer support agent for AI Agent Platform"
  
# Core AI Configuration
ai_config:
  model: "gemini-1.5-pro"
  temperature: 0.7
  max_tokens: 2048
  top_p: 0.9
  
# Language and Localization
language:
  default: "en-US"
  supported_languages:
    - "en-US"
    - "en-GB"
    - "es"
    - "fr"
    - "de"

# Response Configuration
response_settings:
  max_response_time: 30 # seconds
  typing_indicator: true
  conversation_timeout: 1800 # 30 minutes
  
# Integration Settings
integrations:
  google_ai_studio:
    enabled: true
    api_version: "v1"
    
  google_workspace:
    enabled: true
    apps:
      - "gmail"
      - "calendar"
      - "docs"
      - "sheets"
      
  github:
    enabled: true
    webhook_events:
      - "issues"
      - "pull_requests"
      
# Logging and Analytics
logging:
  level: "INFO"
  retention_days: 90
  include_conversation_history: true
  
analytics:
  track_user_satisfaction: true
  track_resolution_time: true
  track_escalation_rate: true
  
# Security Settings
security:
  encryption_at_rest: true
  encryption_in_transit: true
  data_retention_policy: 365 # days
  pii_detection: true
  
# Performance Settings
performance:
  concurrent_conversations: 100
  rate_limit_per_minute: 60
  memory_optimization: true
  
# Agent Behavior
behavior:
  personality: "helpful_professional"
  proactive_suggestions: true
  follow_up_reminders: true
  escalation_threshold: 3 # failed attempts
  
# Knowledge Base
knowledge_base:
  auto_update: true
  sources:
    - "faq_responses.json"
    - "documentation"
    - "previous_conversations"
    
# Monitoring and Health Checks
monitoring:
  health_check_interval: 300 # 5 minutes
  performance_alerts: true
  error_reporting: true
